meta_title: "Datafter l'hommage éternel"
meta_description: "Datafter est une plateforme permettant de rendre hommage aux être chers pour que leur souvenir demeure. Il est possible de rédiger ces mémoires, d'écrire des messages pour laisser une trace de son existence à ses proches"
meta_image: "/assets/images/logos/logo_reverse.png" # Une image dans votre dossier app/assets/images/
twitter_account: "@Datafter"